const patients = [
    {
      fname: 'Ava',
      lname: 'Robinson',
      dob: '1992-10-08',
      age: 30,
      gender: 'Female',
      id: 82701662,
      height: 167,
      weight: 62,
      bloodGroup: 'AB+',
      bmi: 22.2,
      medicalhis: { disease: [ 'High Blood Pressure', 'Cancer' ], allergies: [ 'Pollen' ] },
      familyhis: { fatherside: [ 'Diabetes' ], motherside: [ 'Asthma' ] },
      status: 'Pending'
    },
    {
      fname: 'Ethan',
      lname: 'Garcia',
      dob: '1988-05-17',
      age: 35,
      gender: 'Male',
      id: 19283746,
      height: 185,
      weight: 82,
      bloodGroup: 'O+',
      bmi: 23.9,
      medicalhis: { disease: [ 'Asthma' ], allergies: [ 'Peanuts', 'Seafood' ] },
      familyhis: { fatherside: [ 'Heart Disease' ], motherside: [ 'Depression' ] },
      status: 'Active'
    },
    {
      fname: 'Emma',
      lname: 'Nguyen',
      dob: '1995-02-12',
      age: 28,
      gender: 'Female',
      id: 34567890,
      height: 160,
      weight: 55,
      bloodGroup: 'B-',
      bmi: 21.5,
      medicalhis: { disease: [ 'Migraine', 'Anxiety' ], allergies: [ 'Dust', 'Pollen' ] },
      familyhis: { fatherside: [ 'Arthritis' ], motherside: [ 'High Blood Pressure' ] },
      status: 'Pending'
    },
    {
      fname: 'Noah',
      lname: 'Lee',
      dob: '2001-07-30',
      age: 22,
      gender: 'Male',
      id: 98765432,
      height: 175,
      weight: 70,
      bloodGroup: 'A+',
      bmi: 22.9,
      medicalhis: { disease: ['diabetes'], allergies: [ 'Cats' ] },
      familyhis: { fatherside: [ 'Depression', 'Diabetes' ], motherside: [] },
      status: 'Active'
    },
    {
      fname: 'Sophia',
      lname: 'Wang',
      dob: '1982-12-01',
      age: 41,
      gender: 'Female',
      id: 65432109,
      height: 168,
      weight: 60,
      bloodGroup: 'AB-',
      bmi: 21.3,
      medicalhis: { disease: [ 'Thyroid Disorder' ], allergies: [ 'Shellfish', 'Pollen' ] },
      familyhis: { fatherside: [ 'Heart Disease' ], motherside: [ 'Asthma', 'Arthritis' ] },
      status: 'Pending'
    },
    {
      fname: 'Emma',
      lname: 'Wilson',
      dob: '1987-05-12',
      age: 34,
      gender: 'Female',
      id: 34890872,
      height: 162,
      weight: 55,
      bloodGroup: 'O+',
      bmi: 20.9,
      medicalhis: { disease: [ 'Migraine', 'Depression' ], allergies: [ 'Dust' ] },
      familyhis: { fatherside: [ 'High Cholesterol' ], motherside: [ 'Asthma' ] },
      status: 'Pending'
    },
    {
      fname: 'Ethan',
      lname: 'Lee',
      dob: '1990-12-25',
      age: 31,
      gender: 'Male',
      id: 90285681,
      height: 175,
      weight: 72,
      bloodGroup: 'A-',
      bmi: 23.5,
      medicalhis: { disease: [ 'Diabetes', 'Asthma' ], allergies: [ 'Pollen' ] },
      familyhis: { fatherside: [ 'High Blood Pressure' ], motherside: [ 'Cancer' ] },
      status: 'Pending'
    },
    {
      fname: 'Olivia',
      lname: 'Harris',
      dob: '1985-08-18',
      age: 36,
      gender: 'Female',
      id: 18790564,
      height: 170,
      weight: 68,
      bloodGroup: 'B+',
      bmi: 23.5,
      medicalhis: { disease: [ 'Arthritis', 'Migraine' ], allergies: [ 'Pollen' ] },
      familyhis: { fatherside: [ 'Cancer' ], motherside: [ 'Asthma' ] },
      status: 'Pending'
    },
    {
      fname: 'Aiden',
      lname: 'Nguyen',
      dob: '1993-04-01',
      age: 28,
      gender: 'Male',
      id: 13890576,
      height: 180,
      weight: 80,
      bloodGroup: 'AB-',
      bmi: 24.7,
      medicalhis: { disease: [ 'High Cholesterol', 'Depression' ], allergies: [ 'Dust' ] },
      familyhis: { fatherside: [ 'Diabetes' ], motherside: [ 'Cancer' ] },
      status: 'Pending'
    },
    {
      fname: 'Sophia',
      lname: 'Kim',
      dob: '1995-06-10',
      age: 26,
      gender: 'Female',
      id: 34908654,
      height: 163,
      weight: 56,
      bloodGroup: 'O-',
      bmi: 21,
      medicalhis: { disease: [ 'Asthma', 'High Blood Pressure' ], allergies: [ 'Dust' ] },
      familyhis: { fatherside: [ 'Cancer' ], motherside: [ 'Diabetes' ] },
      status: 'Pending'
    }
  ];

  
  export default patients